#! /bin/sh


sxhkd &
compton &
xbindkeys -f /home/krozic/.config/xbindkeys/.xbindkeysrc &
#1440p.sh &


bspc monitor HDMI1 -n 1 -d I II III IV V &

bspc config merge_overlapping_monitors true &
bspc config remove_disabled_monitor true &


bspc config border_width         1 &
bspc config window_gap          12 &

bspc config focused_border_color "#16d0d0" &
bspc config presel_feedback_color "#16d0d0" &

bspc config split_ratio          0.50 &
bspc config borderless_monocle   true &
bspc config gapless_monocle      false &
bspc config focus_follows_pointer true &
bspc config click_to_focus true &
#bspc config pointer_follows_focus true &

bspc rule -a Gimp desktop='^8' state=floating follow=on &
#bspc rule -a Chromium desktop='^2' &
bspc rule -a mplayer2 state=floating &
bspc rule -a Kupfer.py focus=on &
bspc rule -a Screenkey manage=off &
#bspc rule -a xfce4-terminal --drop-down=floating &
bspc rule -a Qalculate! state=floating &
bspc rule -a qalculate-gtk state=floating &


#Bar set
/home/krozic/.config/polybar/polybar.sh &

# Wallpaper set
feh --bg-fill /home/krozic/Pictures/Wallpapers/outrun.jpg &

# Caps Ctrl Switch
#xmodmap /home/krozic/.config/xmodmap/.xmodmaprc &
setxkbmap -option "ctrl:nocaps" &

# Screensaver
pkill xautolock &
xautolock -locker screensaver.sh -nowlocker screensaver.sh -time 3 &

# Keyboard delay/rate
xset r rate 230 50 &

#paddingreset.py

bspc config top_padding 46 &
bspc config bottom_padding 15 &
bspc config left_padding 0 &
bspc config right_padding 0


